---
- hosts: "node1.example.com"
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
          - secret.yml
  tasks:
  - name: create users
    user:
            name: "{{ item.name }}"
            state: present
            groups: "{{ item.groups }}"
            home: "{{ item.home }}"
            comment: "{{ item.comment }}"
    loop:
     - name: Alice
       groups: users
       home: /home/Alice
       comment: Alice@example.com
       password: "{{ pwhash }}"
     - name: Bob
       groups: users
       home: /home/Bob
       comment: Bob@example.com
       password: "{{ pwhash }}"  
     - name: Carol
       groups: users
       home: /home/Carol
       comment: Carol@example.com
